revert to previous baseline lookup
Signed-off-by: Brian L. Troutwine <brian.troutwine@datadoghq.com>

diff --git a/.gitlab/functional_test/regression_detector.yml b/.gitlab/functional_test/regression_detector.yml
--- a/.gitlab/functional_test/regression_detector.yml
+++ b/.gitlab/functional_test/regression_detector.yml
@@ -106,9 +106,12 @@ single-machine-performance-regression_detector:
     - datadog-ci tag --level job --tags smp_failure_mode:"unknown"
     # Ensure output files exist for artifact downloads step
     - mkdir outputs # Also needed for smp job sync step
-    # Read the baseline SHA from the pre-check job artifact
-    - BASELINE_SHA=$(cat regression_detector_baseline_sha.txt)
-    - echo "Using baseline SHA from pre-check: ${BASELINE_SHA}"
+    # Compute merge base of current commit and `main`
+    - git fetch origin
+    - SMP_BASE_BRANCH=$(dda inv release.get-release-json-value base_branch --no-worktree)
+    - echo "Looking for merge base for branch ${SMP_BASE_BRANCH}"
+    - SMP_MERGE_BASE=$(git merge-base ${CI_COMMIT_SHA} origin/${SMP_BASE_BRANCH})
+    - echo "Merge base is ${SMP_MERGE_BASE}"
     # Setup AWS credentials for single-machine-performance AWS account
     - AWS_NAMED_PROFILE="single-machine-performance"
     - SMP_ACCOUNT_ID=$($CI_PROJECT_DIR/tools/ci/fetch_secret.sh $SMP_ACCOUNT account_id) || exit $?
@@ -123,6 +126,7 @@ single-machine-performance-regression_detector:
     # Download smp binary and prepare it for use
     - aws --profile single-machine-performance s3 cp s3://smp-cli-releases/v${SMP_VERSION}/x86_64-unknown-linux-musl/smp smp
     - chmod +x smp
+    - BASELINE_SHA="${SMP_MERGE_BASE}"
     # Copy the baseline SHA to SMP for debugging purposes later
     - echo -n "${BASELINE_SHA}" > "${CI_COMMIT_SHA}-baseline_sha"
     - aws s3 cp --profile single-machine-performance --only-show-errors "${CI_COMMIT_SHA}-baseline_sha" "s3://${SMP_AGENT_TEAM_ID}-smp-artifacts/information/"
@@ -149,134 +153,134 @@ single-machine-performance-regression_detector:
         datadog-ci tag --level job --tags smp_failure_mode:"job-submission"
         exit $exit_code
       }
-    # # Get the SMP Job Id from 'submission-metadata' and use 'datadog-ci'
-    # # to tag the gitlab job seen in CI Visibility with the SMP Job Id.
-    # - SMP_JOB_ID=$(jq -r '.jobId' submission_metadata)
-    # - echo "SMP Job Id is ${SMP_JOB_ID}"
-    # - datadog-ci tag --level job --tags smp_job_id:${SMP_JOB_ID}
-    # # Wait for job to complete.
-    # - |
-    #   RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
-    #   job status \
-    #   --wait \
-    #   --wait-delay-seconds 60 \
-    #   --submission-metadata submission_metadata || {
-    #     exit_code=$?
-    #     echo "smp job status command failed with code $exit_code"
-    #     datadog-ci tag --level job --tags smp_failure_mode:"job-status"
-    #     exit $exit_code
-    #   }
-    # # Now that the job is completed pull the analysis report, output it to stdout.
-    # - |
-    #   RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
-    #   job sync \
-    #   --submission-metadata submission_metadata \
-    #   --output-path outputs || {
-    #     exit_code=$?
-    #     echo "smp job sync command failed with code $exit_code"
-    #     datadog-ci tag --level job --tags smp_failure_mode:"job-sync"
-    #     exit $exit_code
-    #   }
-    # # Replace empty lines in the output with lines containing various unicode
-    # # space characters. This avoids
-    # # https://gitlab.com/gitlab-org/gitlab/-/issues/217231.
-    # - cat outputs/report.md | sed "s/^\$/$(echo -ne '\uFEFF\u00A0\u200B')/g"
-    # # Upload JUnit XML outside of Agent CI's tooling because the `junit_upload`
-    # # invoke task has additional logic that does not seem to apply well to SMP's
-    # # JUnit XML. Agent CI seems to use `datadog-agent` as the service name when
-    # # uploading JUnit XML, so the upload command below respects that convention.
-    # - datadog-ci junit upload --service datadog-agent outputs/junit.xml
-    # # At this point if the script has not failed the `smp_failure_mode` tag should be none.
-    # # Although this may not be necessarily true, failures as a result of violations in optimization goals
-    # # bounds checks and quality gates will be signaled by their own tag.
-    # - datadog-ci tag --level job --tags smp_failure_mode:"none"
-    # # Check for failing regression detector for the purpose of tagging.
-    # # For consistency we start by tagging with smp_optimization_goal:passed and overwrite to failed if a failure is detected.
-    # - datadog-ci tag --level job --tags smp_optimization_goal:"passed"
-    # - |
-    #   RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
-    #     job result \
-    #     --submission-metadata submission_metadata --signal regression-detector || {
-    #     exit_code=$?
-    #     echo "smp regression detector has detected a regression"
-    #     datadog-ci tag --level job --tags smp_optimization_goal:"failed"
-    #   }
-    # # Check for failing bounds checks for the purpose of tagging.
-    # # For consistency we start by tagging with smp_bounds_check:passed and overwrite to failed if a failure is detected.
-    # - datadog-ci tag --level job --tags smp_bounds_check:"passed"
-    # - |
-    #   RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
-    #     job result \
-    #     --submission-metadata submission_metadata --signal bounds-check || {
-    #     exit_code=$?
-    #     echo "smp regression detector has detected a failed bounds check"
-    #     datadog-ci tag --level job --tags smp_bounds_check:"failed"
-    #   }
-    # # Run quality gate check script
-    # # In order to determine if the following python script failed we assume quality gates failure here and update accordingly
-    # # if we make it through the python script successfully. The consequence of this is that any failure in the python script will
-    # # be seen as a quality gates failure.
-    # - datadog-ci tag --level job --tags smp_quality_gates:"failed"
-    # - |
-    #   python3 <<'EOF'
-    #   import json
-    #   import sys
+    # Get the SMP Job Id from 'submission-metadata' and use 'datadog-ci'
+    # to tag the gitlab job seen in CI Visibility with the SMP Job Id.
+    - SMP_JOB_ID=$(jq -r '.jobId' submission_metadata)
+    - echo "SMP Job Id is ${SMP_JOB_ID}"
+    - datadog-ci tag --level job --tags smp_job_id:${SMP_JOB_ID}
+    # Wait for job to complete.
+    - |
+      RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
+      job status \
+      --wait \
+      --wait-delay-seconds 60 \
+      --submission-metadata submission_metadata || {
+        exit_code=$?
+        echo "smp job status command failed with code $exit_code"
+        datadog-ci tag --level job --tags smp_failure_mode:"job-status"
+        exit $exit_code
+      }
+    # Now that the job is completed pull the analysis report, output it to stdout.
+    - |
+      RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
+      job sync \
+      --submission-metadata submission_metadata \
+      --output-path outputs || {
+        exit_code=$?
+        echo "smp job sync command failed with code $exit_code"
+        datadog-ci tag --level job --tags smp_failure_mode:"job-sync"
+        exit $exit_code
+      }
+    # Replace empty lines in the output with lines containing various unicode
+    # space characters. This avoids
+    # https://gitlab.com/gitlab-org/gitlab/-/issues/217231.
+    - cat outputs/report.md | sed "s/^\$/$(echo -ne '\uFEFF\u00A0\u200B')/g"
+    # Upload JUnit XML outside of Agent CI's tooling because the `junit_upload`
+    # invoke task has additional logic that does not seem to apply well to SMP's
+    # JUnit XML. Agent CI seems to use `datadog-agent` as the service name when
+    # uploading JUnit XML, so the upload command below respects that convention.
+    - datadog-ci junit upload --service datadog-agent outputs/junit.xml
+    # At this point if the script has not failed the `smp_failure_mode` tag should be none.
+    # Although this may not be necessarily true, failures as a result of violations in optimization goals
+    # bounds checks and quality gates will be signaled by their own tag.
+    - datadog-ci tag --level job --tags smp_failure_mode:"none"
+    # Check for failing regression detector for the purpose of tagging.
+    # For consistency we start by tagging with smp_optimization_goal:passed and overwrite to failed if a failure is detected.
+    - datadog-ci tag --level job --tags smp_optimization_goal:"passed"
+    - |
+      RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
+        job result \
+        --submission-metadata submission_metadata --signal regression-detector || {
+        exit_code=$?
+        echo "smp regression detector has detected a regression"
+        datadog-ci tag --level job --tags smp_optimization_goal:"failed"
+      }
+    # Check for failing bounds checks for the purpose of tagging.
+    # For consistency we start by tagging with smp_bounds_check:passed and overwrite to failed if a failure is detected.
+    - datadog-ci tag --level job --tags smp_bounds_check:"passed"
+    - |
+      RUST_LOG="${RUST_LOG}" ./smp --team-id ${SMP_AGENT_TEAM_ID} --api-base ${SMP_API} --aws-named-profile ${AWS_NAMED_PROFILE} \
+        job result \
+        --submission-metadata submission_metadata --signal bounds-check || {
+        exit_code=$?
+        echo "smp regression detector has detected a failed bounds check"
+        datadog-ci tag --level job --tags smp_bounds_check:"failed"
+      }
+    # Run quality gate check script
+    # In order to determine if the following python script failed we assume quality gates failure here and update accordingly
+    # if we make it through the python script successfully. The consequence of this is that any failure in the python script will
+    # be seen as a quality gates failure.
+    - datadog-ci tag --level job --tags smp_quality_gates:"failed"
+    - |
+      python3 <<'EOF'
+      import json
+      import sys
 
-    #   try:
-    #       with open('outputs/report.json') as f:
-    #           data = json.load(f)
-    #   except FileNotFoundError:
-    #       print("Machine readable report not found.")
-    #       sys.exit(1)
-    #   except json.JSONDecodeError as e:
-    #       print(f"Error parsing JSON report: {e}")
-    #       sys.exit(1)
+      try:
+          with open('outputs/report.json') as f:
+              data = json.load(f)
+      except FileNotFoundError:
+          print("Machine readable report not found.")
+          sys.exit(1)
+      except json.JSONDecodeError as e:
+          print(f"Error parsing JSON report: {e}")
+          sys.exit(1)
 
-    #   experiments = data.get('experiments', {})
-    #   failed = False
-    #   decision_record = []
+      experiments = data.get('experiments', {})
+      failed = False
+      decision_record = []
 
-    #   for exp_name, exp_data in experiments.items():
-    #       if exp_name.startswith('quality_gate_'):
-    #           bounds_checks = exp_data.get('bounds_checks', {})
-    #           for check_name, check_data in bounds_checks.items():
-    #               results = check_data.get('results', {})
-    #               comparison = results.get('comparison', [])
-    #               num_total = len(comparison)
-    #               failed_replicates = [
-    #                   replicate for replicate in comparison if not replicate.get('passed', False)
-    #               ]
-    #               num_failed = len(failed_replicates)
-    #               num_passed = num_total - num_failed
-    #               if failed_replicates:
-    #                   decision_record.append(
-    #                       f"- **{exp_name}**, bounds check **{check_name}**: {num_passed}/{num_total} replicas passed. Failed {num_failed} which is > 0. Gate **FAILED**."
-    #                   )
-    #                   failed = True
-    #               else:
-    #                   decision_record.append(
-    #                       f"- **{exp_name}**, bounds check **{check_name}**: {num_passed}/{num_total} replicas passed. Gate passed."
-    #                   )
+      for exp_name, exp_data in experiments.items():
+          if exp_name.startswith('quality_gate_'):
+              bounds_checks = exp_data.get('bounds_checks', {})
+              for check_name, check_data in bounds_checks.items():
+                  results = check_data.get('results', {})
+                  comparison = results.get('comparison', [])
+                  num_total = len(comparison)
+                  failed_replicates = [
+                      replicate for replicate in comparison if not replicate.get('passed', False)
+                  ]
+                  num_failed = len(failed_replicates)
+                  num_passed = num_total - num_failed
+                  if failed_replicates:
+                      decision_record.append(
+                          f"- **{exp_name}**, bounds check **{check_name}**: {num_passed}/{num_total} replicas passed. Failed {num_failed} which is > 0. Gate **FAILED**."
+                      )
+                      failed = True
+                  else:
+                      decision_record.append(
+                          f"- **{exp_name}**, bounds check **{check_name}**: {num_passed}/{num_total} replicas passed. Gate passed."
+                      )
 
-    #   with open('outputs/decision_record.md', 'w') as f:
-    #       # Extra newline since this is appended to another report
-    #       f.write('\n\n## CI Pass/Fail Decision\n\n')
-    #       if failed:
-    #           f.write('❌ **Failed.** Some Quality Gates were violated.\n\n')
-    #           f.write('\n'.join(decision_record))
-    #       else:
-    #           f.write('✅ **Passed.** All Quality Gates passed.\n\n')
-    #           f.write('\n'.join(decision_record))
+      with open('outputs/decision_record.md', 'w') as f:
+          # Extra newline since this is appended to another report
+          f.write('\n\n## CI Pass/Fail Decision\n\n')
+          if failed:
+              f.write('❌ **Failed.** Some Quality Gates were violated.\n\n')
+              f.write('\n'.join(decision_record))
+          else:
+              f.write('✅ **Passed.** All Quality Gates passed.\n\n')
+              f.write('\n'.join(decision_record))
 
-    #   if failed:
-    #       print("Quality gate failed, see decision record")
-    #       sys.exit(1)
-    #   else:
-    #       print("Quality gate passed.")
-    #       sys.exit(0)
-    #   EOF
-    # # If we make it here that means quality gates must not have failed.
-    # - datadog-ci tag --level job --tags smp_quality_gates:"passed"
+      if failed:
+          print("Quality gate failed, see decision record")
+          sys.exit(1)
+      else:
+          print("Quality gate passed.")
+          sys.exit(0)
+      EOF
+    # If we make it here that means quality gates must not have failed.
+    - datadog-ci tag --level job --tags smp_quality_gates:"passed"
 
 # Shamelessly adapted from golang_deps_commenter job config in
 # golang_deps_diff.yml at commit 01da274032e510d617161cf4e264a53292f44e55.
