test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,13 +2,25 @@ test_gitlab:
   stage: test
   tags: ["macos:monterey-amd64", "specific:true"]
   script:
-    - echo "Running tests"
-    - pyenv virtualenvs --bare
-    - which grep
-    - ls toto || true
-    - pyenv virtualenvs --bare | grep "datadog-agent-python-3.11"
-    - echo "toto" | grep -q "toto"
-    - grep -q "toto" <<< "toto"
-    - grep --help
+  - |
+    PYTHON_REPO_VERSION=$(cat .python-version)
+    PYTHON_VERSION=$(python3 --version | awk '{print $2}' | sed 's/\.[0-9]*$//')
+    VENV_NAME="datadog-agent-python-$PYTHON_VERSION"
+    if [ "$PYTHON_REPO_VERSION" != "$PYTHON_VERSION" ]; then
+      echo "Warning: The current Python version $PYTHON_VERSION is different from $PYTHON_REPO_VERSION in .python-version."
+      echo "Installing Python $PYTHON_REPO_VERSION..."
+    fi
+    ## START TEMPORARY DEBUG see ACIX-500
+    echo $PYTHON_VERSION
+    echo $VENV_NAME
+    pyenv virtualenvs --bare
+    ls $(pyenv root)/versions/
+    ## END TEMPORARY DEBUG see ACIX-500
+    if ! pyenv virtualenvs --bare | grep -q "^${VENV_NAME}$"; then
+      # The || true is a quickfix avoiding the command to fail if the virtualenv already exists
+      # This should be removed once ACIX-500 is done
+      pyenv virtualenv $PYTHON_VERSION $VENV_NAME || true
+    fi
+    pyenv activate $VENV_NAME
 
 
