[precommit-set-x] Added rule

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -100,3 +100,19 @@ repos:
       always_run: true
       pass_filenames: false
       stages: [pre-push]
+    - id: shell-set-x
+      name: shell-set-x
+      description: check that no `set -x` is set within github / gitlab workflows
+      entry: |
+        bash -c "
+          grep -rn 'set -x' --include '*.yaml' --include '*.sh' --include 'Dockerfile' --exclude .pre-commit-config.yaml --color=auto
+          if [ "$?" = 0 ]; then
+            echo -e '\nerror: No script should include `set -x`'
+            exit 1
+          else
+            exit 0
+          fi
+          "
+      language: system
+      require_serial: true
+      files: (\.yaml|\.sh|Dockerfile)$
