[CI][macOS runners] Temporary never fail on virtualenv already exists error + debug messages

diff --git a/.gitlab/common/macos.yml b/.gitlab/common/macos.yml
--- a/.gitlab/common/macos.yml
+++ b/.gitlab/common/macos.yml
@@ -28,8 +28,15 @@
       echo "Warning: The current Python version $PYTHON_VERSION is different from $PYTHON_REPO_VERSION in .python-version."
       echo "Installing Python $PYTHON_REPO_VERSION..."
     fi
+    ## START TEMPORARY DEBUG see ACIX-500
+    echo $PYTHON_VERSION
+    echo $VENV_NAME
+    pyenv virtualenvs --bare
+    ## END TEMPORARY DEBUG see ACIX-500
     if ! pyenv virtualenvs --bare | grep -q "^${VENV_NAME}$"; then
-      pyenv virtualenv $PYTHON_VERSION $VENV_NAME
+      # The || true is a quickfix avoiding the command to fail if the virtualenv already exists
+      # This should be removed once ACIX-500 is done
+      pyenv virtualenv $PYTHON_VERSION $VENV_NAME || true
     fi
     pyenv activate $VENV_NAME
 
