[add-skip-ci-mq-check] Cleaned code

diff --git a/.gitlab/common/skip_ci_check.yml b/.gitlab/common/skip_ci_check.yml
--- a/.gitlab/common/skip_ci_check.yml
+++ b/.gitlab/common/skip_ci_check.yml
@@ -5,16 +5,16 @@ skip-ci-check:
   needs: []
   stage: setup
   tags: ["arch:amd64"]
-  # rules:
-  #   - !reference [.except_mergequeue]
-  #   - when: on_success
+  rules:
+    - !reference [.except_mergequeue]
+    - when: on_success
   script:
     - commit_message="$(git log --format=%B -n 1 $CI_COMMIT_SHA)"
     # https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
     - |
       case "$commit_message" in
-          *"[add-skip-ci-mq-check]"*|*"[ci skip]"*|*"[skip ci]"*|*"[actions skip]"*|*"[skip actions]"*|*"[no ci]"*|*"skip-checks: true"*|*"skip-checks:true"*)
-              echo "error: Do not skip checks when merging PRs" >& 2
+          *"[ci skip]"*|*"[skip ci]"*|*"[actions skip]"*|*"[skip actions]"*|*"[no ci]"*|*"skip-checks: true"*|*"skip-checks:true"*)
+              echo "error: The commit message of this PR contains ci skip tags. Do not skip checks when merging PRs, please change the description of the merge commit" >& 2
               exit 1
           ;;
       esac
