Update .gitlab/common/skip_ci_check.yml
Co-authored-by: Lénaïc Huard <L3n41c@users.noreply.github.com>

diff --git a/.gitlab/common/skip_ci_check.yml b/.gitlab/common/skip_ci_check.yml
--- a/.gitlab/common/skip_ci_check.yml
+++ b/.gitlab/common/skip_ci_check.yml
@@ -12,11 +12,9 @@ skip-ci-check:
     - commit_message="$(git log --format=%B -n 1 $CI_COMMIT_SHA)"
     # https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
     - |
-      case "$commit_message" in
-          *"[ci skip]"*|*"[skip ci]"*|*"[actions skip]"*|*"[skip actions]"*|*"[no ci]"*|*"skip-checks: true"*|*"skip-checks:true"*)
-              echo "error: The commit message of this PR contains ci skip tags. Do not skip checks when merging PRs, please change the description of the merge commit" >& 2
-              exit 1
-          ;;
-      esac
+      if [[ "$commit_message" =~ *"[ci skip]"*|*"[skip ci]"*|*"[actions skip]"*|*"[skip actions]"*|*"[no ci]"*|*"skip-checks: true"*|*"skip-checks:true"* ]]; then
+            echo "error: The commit message of this PR contains ci skip tags. Do not skip checks when merging PRs, please change the description of the merge commit" >& 2
+            exit 1
+      fi
     - "echo 'success: No check skip found'"
 
