[kitchen] Add SUSE 11 kitchen tests (#4531)
Adds kitchen tests for SUSE 11 with sysvinit.
Fixes problems with said sysvinit scripts.

A5 upgrade tests are disabled for now because the A5
install-script does not work on SUSE 11.
A6 upgrade tests are disabled for now as we don't have
a stable A6 version supporting SUSE 11 yet.

diff --git a/omnibus/package-scripts/agent/posttrans b/omnibus/package-scripts/agent/posttrans
--- a/omnibus/package-scripts/agent/posttrans
+++ b/omnibus/package-scripts/agent/posttrans
@@ -24,7 +24,7 @@ if [ "$DISTRIBUTION_FAMILY" == "SUSE" ]; then
     # (even if they're not used) as it cannot process them (a package necessary to process them
     # was removed from the base distribution).
     if cat /etc/SuSE-release 2>/dev/null | grep VERSION | grep 11; then
-        SYSVINIT_SUPPORT="yes"
+        SUSE_SYSVINIT_SUPPORT="yes"
     else
         rm -f /etc/init.d/datadog-agent
         rm -f /etc/init.d/datadog-agent-process
@@ -41,10 +41,16 @@ if command -v systemctl >/dev/null 2>&1; then
 elif command -v initctl >/dev/null 2>&1; then
     # start/stop policy is already defined in the upstart job file
     :
-elif command -v update-rc.d >/dev/null 2>&1; then
-    update-rc.d $SERVICE_NAME defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with update-rc.d"
-    update-rc.d $SERVICE_NAME-process defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-process with update-rc.d"
-    update-rc.d $SERVICE_NAME-trace defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-trace with update-rc.d"
+elif [ "$SUSE_SYSVINIT_SUPPORT" = "yes" ]; then
+    if command -v update-rc.d >/dev/null 2>&1; then
+        update-rc.d $SERVICE_NAME defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with update-rc.d"
+        update-rc.d $SERVICE_NAME-process defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-process with update-rc.d"
+        update-rc.d $SERVICE_NAME-trace defaults || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-trace with update-rc.d"
+    else
+        ln -s /etc/init.d/$SERVICE_NAME /etc/init.d/rc5.d/S95$SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME"
+        ln -s /etc/init.d/$SERVICE_NAME-process /etc/init.d/rc5.d/S95$SERVICE_NAME-process || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-process"
+        ln -s /etc/init.d/$SERVICE_NAME-trace /etc/init.d/rc5.d/S95$SERVICE_NAME-trace || echo "[ WARNING ]\tCannot enable $SERVICE_NAME-trace"
+    fi
 else
     echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
 fi
@@ -57,7 +63,7 @@ if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
         systemctl restart $SERVICE_NAME || true
     elif command -v initctl >/dev/null 2>&1; then
         initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
-    elif [ "$SYSVINIT_SUPPORT" == "yes" ] && command -v service >/dev/null 2>&1; then
+    elif [ "$SUSE_SYSVINIT_SUPPORT" = "yes" ] && command -v service >/dev/null 2>&1; then
         service $SERVICE_NAME restart || true
     else
         echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
