improve(omnibus) applied branding on build script

diff --git a/omnibus/package-scripts/agent/postinst b/omnibus/package-scripts/agent/postinst
--- a/omnibus/package-scripts/agent/postinst
+++ b/omnibus/package-scripts/agent/postinst
@@ -1,22 +1,22 @@
 #!/bin/sh
 #
-# Perform necessary datadog-agent setup steps after package is installed.
+# Perform necessary stackstate-agent setup steps after package is installed.
 # NOTE: for .rpm, see posttrans instead
 #
 # .deb: STEP 2 of 5
 # .rpm: STEP 3 of 6
 
-INSTALL_DIR=/opt/datadog-agent
-LOG_DIR=/var/log/datadog
-CONFIG_DIR=/etc/datadog-agent
-SERVICE_NAME=datadog-agent
+INSTALL_DIR=/opt/stackstate-agent
+LOG_DIR=/var/log/stackstate
+CONFIG_DIR=/etc/stackstate-agent
+SERVICE_NAME=stackstate-agent
 
 KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE)"
 DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || grep -m1 -Eo $KNOWN_DISTRIBUTION /etc/os-release 2>/dev/null || uname -s)
 
 # If we are inside the Docker container, do nothing
-if [ -n "$DOCKER_DD_AGENT" ]; then
-    echo "Installation from docker-dd-agent, nothing to do in postinst"
+if [ -n "$DOCKER_STS_AGENT" ]; then
+    echo "Installation from docker-sts-agent, nothing to do in postinst"
     exit 0
 fi
 
@@ -30,23 +30,23 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
         set -e
         case "$1" in
             configure)
-                # Only create dd-agent group and/or user if they don't already exist
-                getent group dd-agent >/dev/null || (echo "Creating dd-agent group" && addgroup --system dd-agent --quiet)
+                # Only create sts-agent group and/or user if they don't already exist
+                getent group sts-agent >/dev/null || (echo "Creating sts-agent group" && addgroup --system sts-agent --quiet)
                 set +e
-                id -u dd-agent >/dev/null 2>&1
+                id -u sts-agent >/dev/null 2>&1
                 USER_EXISTS=$?
                 set -e
                 if [ ! $USER_EXISTS -eq 0 ]; then
-                    echo "Creating dd-agent user"
-                    adduser --system dd-agent --disabled-login --shell /usr/sbin/nologin --home ${INSTALL_DIR} --no-create-home --group --quiet
-                elif id -nG dd-agent | grep --invert-match --word-regexp --quiet 'dd-agent'; then
-                    # User exists but is not part of the dd-agent group
-                    echo "Adding dd-agent user to dd-agent group"
-                    usermod -g dd-agent dd-agent
+                    echo "Creating sts-agent user"
+                    adduser --system sts-agent --disabled-login --shell /usr/sbin/nologin --home ${INSTALL_DIR} --no-create-home --group --quiet
+                elif id -nG sts-agent | grep --invert-match --word-regexp --quiet 'sts-agent'; then
+                    # User exists but is not part of the sts-agent group
+                    echo "Adding sts-agent user to sts-agent group"
+                    usermod -g sts-agent sts-agent
                 fi
 
                 # Create a symlink to the agent's binary
-                ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/datadog-agent
+                ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/stackstate-agent
             ;;
             abort-upgrade|abort-remove|abort-deconfigure)
             ;;
@@ -57,10 +57,10 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
         #DEBHELPER#
     fi
 
-    # Set proper rights to the dd-agent user
-    chown -R dd-agent:dd-agent ${CONFIG_DIR}
-    chown -R dd-agent:dd-agent ${LOG_DIR}
-    chown -R dd-agent:dd-agent ${INSTALL_DIR}
+    # Set proper rights to the sts-agent user
+    chown -R sts-agent:sts-agent ${CONFIG_DIR}
+    chown -R sts-agent:sts-agent ${LOG_DIR}
+    chown -R sts-agent:sts-agent ${INSTALL_DIR}
 
     # Enable and restart the agent service here on Debian platforms
     # On RHEL, this is done in the posttrans script
@@ -75,32 +75,32 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
             # Nothing to do, this is defined directly in the upstart job file
             :
         else
-            echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
+            echo "[ WARNING ]\tCannot detect a supported init system. The stackstate-agent package only provides service files for systemd and upstart."
         fi
 
         # TODO: Use a configcheck command on the agent to determine if it's safe to restart,
         # and avoid restarting when a check conf is invalid
-        if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
+        if [ -f "$CONFIG_DIR/stackstate.yaml" ]; then
             echo "(Re)starting $SERVICE_NAME now..."
             if command -v systemctl >/dev/null 2>&1; then
                 systemctl restart $SERVICE_NAME || true
             elif command -v initctl >/dev/null 2>&1; then
                 initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
             else
-                echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
+                echo "[ WARNING ]\tCannot detect a supported init system. The stackstate-agent package only provides service files for systemd and upstart."
             fi
         else
-            # No datadog.yaml file is present. This is probably a clean install made with the
+            # No stackstate.yaml file is present. This is probably a clean install made with the
             # step-by-step instructions/an automation tool, and the config file will be added next.
-            echo "No datadog.yaml file detected, not starting the agent"
+            echo "No stackstate.yaml file detected, not starting the agent"
         fi
     fi
 else
     # macOS
 
     # macOS-specific variables
-    OPT_APP_DIR="$INSTALL_DIR/Datadog Agent.app"
-    APP_DIR="/Applications/Datadog Agent.app"
+    OPT_APP_DIR="$INSTALL_DIR/Stackstate Agent.app"
+    APP_DIR="/Applications/Stackstate Agent.app"
     CONF_DIR=$INSTALL_DIR/etc
     RUN_DIR=$INSTALL_DIR/run
 
@@ -112,7 +112,7 @@ else
     # Let's talk to our user installing the Agent a bit
     echo "# State at the beginning"
     echo "## Agent version"
-    datadog-agent version || echo "No datadog-agent binary version (agent 6)"
+    stackstate-agent version || echo "No stackstate-agent binary version (agent 6)"
     echo "## $INSTALL_DIR"
     ls -al $INSTALL_DIR || "No agent installed"
     echo "## $APP_DIR/Contents/Resources"
@@ -125,8 +125,8 @@ else
     # If it fails, no choice but to use root :'(
     if [ -z "$INSTALL_USER" ] || [ "$INSTALL_USER" = "root" ]; then
         SCRIPT_INSTALL="yes"
-        INSTALL_USER=`cat /tmp/datadog-install-user || echo 'root'`
-        rm -v /tmp/datadog-install-user || true
+        INSTALL_USER=`cat /tmp/stackstate-install-user || echo 'root'`
+        rm -v /tmp/stackstate-install-user || true
     fi
     echo "INSTALL_USER: $INSTALL_USER"
 
@@ -145,36 +145,36 @@ else
     echo "# Copying conf"
     mkdir -vp $CONF_DIR/checks.d
 
-    if [ -e "/tmp/datadog.conf" ] || [ -e "/tmp/datadog.yaml" ]; then
-        mv -vf /tmp/datadog.conf /tmp/datadog.yaml $CONF_DIR
+    if [ -e "/tmp/stackstate.conf" ] || [ -e "/tmp/stackstate.yaml" ]; then
+        mv -vf /tmp/stackstate.conf /tmp/stackstate.yaml $CONF_DIR
         cp -vfR /tmp/conf.d/* $CONF_DIR/conf.d
         cp -vn /tmp/checks.d/* $CONF_DIR/checks.d
-        rm -vrf /tmp/datadog.conf /tmp/conf.d /tmp/checks.d
+        rm -vrf /tmp/stackstate.conf /tmp/conf.d /tmp/checks.d
     fi
     # Or copying default
-    if [ ! -e "$CONF_DIR/datadog.yaml" ]; then
-        sed -E 's/^api_key:$/api_key: APIKEY/' $CONF_DIR/datadog.yaml.example > $CONF_DIR/datadog.yaml
+    if [ ! -e "$CONF_DIR/stackstate.yaml" ]; then
+        sed -E 's/^api_key:$/api_key: APIKEY/' $CONF_DIR/stackstate.yaml.example > $CONF_DIR/stackstate.yaml
     fi
 
     echo "# Setting correct rights on conf"
     chown -vR $INSTALL_USER:admin $CONF_DIR
 
-    # `datadog-agent` command line
+    # `stackstate-agent` command line
     mkdir -vp /usr/local/bin
-    ln -vs $INSTALL_DIR/bin/agent/agent /usr/local/bin/datadog-agent
+    ln -vs $INSTALL_DIR/bin/agent/agent /usr/local/bin/stackstate-agent
 
     # Link for conf files (let's ease the user's life)
     USER_HOME=`sudo -Hu $INSTALL_USER sh -c 'echo $HOME'`
-    sudo -Hu $INSTALL_USER mkdir -vp "$USER_HOME/.datadog-agent"
-    rm -vf "$USER_HOME/.datadog-agent/conf.d" "$USER_HOME/.datadog-agent/datadog.yaml" "$USER_HOME/.datadog-agent/checks.d"
-    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/conf.d "$USER_HOME/.datadog-agent/conf.d"
-    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/datadog.yaml "$USER_HOME/.datadog-agent/datadog.yaml"
-    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/checks.d "$USER_HOME/.datadog-agent/checks.d"
+    sudo -Hu $INSTALL_USER mkdir -vp "$USER_HOME/.stackstate-agent"
+    rm -vf "$USER_HOME/.stackstate-agent/conf.d" "$USER_HOME/.stackstate-agent/stackstate.yaml" "$USER_HOME/.stackstate-agent/checks.d"
+    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/conf.d "$USER_HOME/.stackstate-agent/conf.d"
+    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/stackstate.yaml "$USER_HOME/.stackstate-agent/stackstate.yaml"
+    sudo -Hu $INSTALL_USER ln -vs $CONF_DIR/checks.d "$USER_HOME/.stackstate-agent/checks.d"
 
     # Error if app not properly installed or root
     if [ "$INSTALL_USER" = "root" ]; then
-        echo 'INSTALL_USER is set to root, Datadog Agent app has been installed'
-        echo 'but is not configured. Running Datadog Agent as root is not advised!'
+        echo 'INSTALL_USER is set to root, Stackstate Agent app has been installed'
+        echo 'but is not configured. Running Stackstate Agent as root is not advised!'
         exit 1
     fi
 
@@ -183,7 +183,7 @@ else
     sudo -Hu $INSTALL_USER cp -vf "$CONF_DIR/com.datadoghq.agent.plist.example" "$USER_HOME/Library/LaunchAgents/com.datadoghq.agent.plist"
     sudo -Hu $INSTALL_USER launchctl load -w "$USER_HOME/Library/LaunchAgents/com.datadoghq.agent.plist"
 
-    if [ ! -e "$CONF_DIR/datadog.yaml" ]; then
+    if [ ! -e "$CONF_DIR/stackstate.yaml" ]; then
         exit 1
     fi
 
@@ -192,17 +192,17 @@ else
         echo "# Starting the app"
         # -a for application, -F for fresh, do not restore old app
         export TMPDIR=`sudo -u $INSTALL_USER getconf DARWIN_USER_TEMP_DIR`
-        sudo -u $INSTALL_USER open -Fa 'Datadog Agent'
+        sudo -u $INSTALL_USER open -Fa 'Stackstate Agent'
     fi
 
     echo "# Configuring the login launch of the app"
-    sudo -u $INSTALL_USER osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Datadog Agent.app", name:"Datadog Agent", hidden:false}'
+    sudo -u $INSTALL_USER osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Stackstate Agent.app", name:"StackstateAgent", hidden:false}'
 
     # A little debriefing won't hurt
     echo "# State at the end"
     echo "## Agent version"
     grep AGENT_VERSION $INSTALL_DIR/agent/config.py || echo "No config.py file (agent 5)"
-    datadog-agent version || echo "No datadog-agent binary version (agent 6)"
+    stackstate-agent version || echo "No stackstate-agent binary version (agent 6)"
     echo "## $INSTALL_DIR"
     ls -al $INSTALL_DIR || echo "No agent installed :("
     echo "## $APP_DIR/Contents/Resources"
