Add sysvinit support to package scripts

diff --git a/omnibus/package-scripts/agent/preinst b/omnibus/package-scripts/agent/preinst
--- a/omnibus/package-scripts/agent/preinst
+++ b/omnibus/package-scripts/agent/preinst
@@ -11,7 +11,9 @@ SERVICE_NAME=datadog-agent
 
 KNOWN_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|Arista|SUSE)"
 DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || grep -Eo $KNOWN_DISTRIBUTION /etc/Eos-release 2>/dev/null || grep -m1 -Eo $KNOWN_DISTRIBUTION /etc/os-release 2>/dev/null || uname -s)
-
+if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" = "Debian" ] || [ "$DISTRIBUTION" = "Ubuntu" ]; then
+    DISTRIBUTION_FAMILY="Debian"
+fi
 # Linux installation
 if [ "$DISTRIBUTION" != "Darwin" ]; then
     set -e
@@ -27,6 +29,14 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
             initctl stop $SERVICE_NAME-process || true
             initctl stop $SERVICE_NAME-trace || true
             initctl stop $SERVICE_NAME || true
+        elif [ "$DISTRIBUTION_FAMILY" = "Debian" ]; then
+            if command -v service >/dev/null 2>&1; then
+                service $SERVICE_NAME-process stop|| true
+                service $SERVICE_NAME-trace stop|| true
+                service $SERVICE_NAME stop || true
+            else
+                echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd, upstart and sysvinit."
+            fi
         else
             echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
         fi
