[packaging] do not fail on inability to lock dd-agent user, just warn
[reno] adding release note + move other to right locaiton

[omnibus][preinst] removing undefined coloring vars

diff --git a/omnibus/package-scripts/agent/preinst b/omnibus/package-scripts/agent/preinst
--- a/omnibus/package-scripts/agent/preinst
+++ b/omnibus/package-scripts/agent/preinst
@@ -48,7 +48,7 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
         getent passwd dd-agent >/dev/null || \
             useradd -r -M -g dd-agent -d $INSTALL_DIR -s /sbin/nologin \
                 -c "Datadog Agent" dd-agent && \
-            usermod -L dd-agent
+                { usermod -L dd-agent || echo "[ WARNING ]\tCannot lock the 'dd-agent' user account"; }
 
         # Delete all the .pyc/.pyo files in the embedded dir that are part of the old agent's package
         if [ -f "$INSTALL_DIR/embedded/.py_compiled_files.txt" ]; then
@@ -56,7 +56,7 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
             cat $INSTALL_DIR/embedded/.py_compiled_files.txt | grep -v '^#' | xargs rm -f
         fi
     else
-        echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
+        echo "[ FAILED ]\tYour system is currently not supported by this script.";
         exit 1;
     fi
 else
