fix(kmt): warn and tag instance-not-found before KMT test jobs fail on ssh
When the metal instance backing a KMT test job is gone by test time, the
job failed with a misleading ssh: Could not resolve hostname metal_instance
error and was tagged infra_ssh-config, masking the real cause.

diff --git a/.gitlab/test/kernel_matrix_testing/common.yml b/.gitlab/test/kernel_matrix_testing/common.yml
--- a/.gitlab/test/kernel_matrix_testing/common.yml
+++ b/.gitlab/test/kernel_matrix_testing/common.yml
@@ -287,8 +287,10 @@
     - RUNNING_INSTANCES=$(aws ec2 describe-instances --filters $FILTER_TEAM $FILTER_MANAGED $FILTER_PIPELINE $FILTER_TEST_COMPONENT "Name=private-ip-address,Values=$INSTANCE_IP" --output text --query $QUERY_INSTANCE_IDS | wc -l )
     - |
       if [ $RUNNING_INSTANCES -eq "0" ]; then
+        echo "WARNING: the metal instance for this job could not be found, provisioning must have failed or the instance was cleaned up before the test ran."
         echo "These jobs do not permit retries. The go tests are retried a user-specified number of times automatically. In order to re-run the tests, you must trigger the pipeline again"
-        'false'
+        touch ${CI_PROJECT_DIR}/instance_not_found
+        exit 1
       fi
     - MICRO_VM_IP=$(jq --exit-status --arg TAG $TAG --arg ARCH $ARCH --arg TEST_SET $TEST_SET -r '.[$ARCH].microvms | map(select(."vmset-tags"| index($TEST_SET))) | map(select(.tag==$TAG)) | .[].ip' $CI_PROJECT_DIR/stack.output)
     - MICRO_VM_NAME=$(jq --exit-status --arg TAG $TAG --arg ARCH $ARCH --arg TEST_SET $TEST_SET -r '.[$ARCH].microvms | map(select(."vmset-tags"| index($TEST_SET))) | map(select(.tag==$TAG)) | .[].id' $CI_PROJECT_DIR/stack.output)
