Do not start the security-agent binary if its configuration file does not exist

diff --git a/omnibus/config/templates/datadog-agent/sysvinit_suse.security.erb b/omnibus/config/templates/datadog-agent/sysvinit_suse.security.erb
--- a/omnibus/config/templates/datadog-agent/sysvinit_suse.security.erb
+++ b/omnibus/config/templates/datadog-agent/sysvinit_suse.security.erb
@@ -15,6 +15,7 @@ INSTALL_DIR="<%= install_dir %>"
 AGENTPATH="$INSTALL_DIR/embedded/bin/security-agent"
 PIDFILE="$INSTALL_DIR/run/security-agent.pid"
 AGENT_ARGS="start -c=$ETC_DIR/datadog.yaml -p=$PIDFILE"
+SECURITY_AGENT_CONFIG_FILE="$ETC_DIR/security-agent.yaml"
 NAME="datadog-agent-security"
 DESC="Datadog Security Agent"
 
@@ -57,6 +58,11 @@ rc_reset
 if [ ! -x $AGENTPATH ]; then
   echo "$AGENTPATH not found. Exiting."
   exit 1
+fi
+
+if [ ! -x $SECURITY_AGENT_CONFIG_FILE ]; then
+	echo "$SECURITY_AGENT_CONFIG_FILE not found. Exiting."
+	exit 1
 fi
 
 if [ -r "/etc/default/${NAME}" ]; then
