update tests

diff --git a/tasks/unit-tests/testdata/fake_circleci_config.yml b/tasks/unit-tests/testdata/fake_circleci_config.yml
--- a/tasks/unit-tests/testdata/fake_circleci_config.yml
+++ b/tasks/unit-tests/testdata/fake_circleci_config.yml
@@ -15,7 +15,7 @@ experimental:
 templates:
   job_template: &job_template
     docker:
-      - image: gcr.io/datadoghq/agent-circleci-runner:v17660676-da3ba55
+      - image: gcr.io/datadoghq/agent-circleci-runner:v32368242-2e3b6ef4
         environment:
           USE_SYSTEM_LIBS: "1"
     working_directory: /go/src/github.com/DataDog/datadog-agent
@@ -29,11 +29,11 @@ templates:
           # If incremental dep fails, increase the cache gen number
           # in restore_deps AND save_deps
           # See https://github.com/DataDog/datadog-agent/pull/2384
-          - gen19-godeps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum ".circleci/images/runner/Dockerfile" }}-{{ .Branch }}-{{ .Revision }}
-          - gen19-godeps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum ".circleci/images/runner/Dockerfile" }}-{{ .Branch }}-
-          - gen19-godeps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum ".circleci/images/runner/Dockerfile" }}-main-
+          - gen19-godeps-{{ checksum ".circleci/config.yml" }}-{{ .Branch }}-{{ .Revision }}
+          - gen19-godeps-{{ checksum ".circleci/config.yml" }}-{{ .Branch }}-
+          - gen19-godeps-{{ checksum ".circleci/config.yml" }}-main-
     - save_cache: &save_deps
-        key: gen19-godeps-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/requirements.txt" }}-{{ checksum ".circleci/images/runner/Dockerfile" }}-{{ .Branch }}-{{ .Revision }}
+        key: gen19-godeps-{{ checksum ".circleci/config.yml" }}-{{ .Branch }}-{{ .Revision }}
     - restore_cache: &restore_source
         keys:
           # Cache retrieval is faster than full git checkout
@@ -58,12 +58,6 @@ jobs:
     steps:
       - restore_cache: *restore_source
       - restore_cache: *restore_deps
-      - run:
-          name: setup python deps
-          command: |
-            python3 -m pip install wheel
-            python3 -m pip install -r requirements.txt
-            python3 -m pip install -r .circleci/requirements.txt
       - run:
           name: check go version
           command: |
@@ -95,7 +89,6 @@ jobs:
             - /go/pkg/mod
             - /go/bin
             - /go/src/github.com/DataDog/datadog-agent/dev
-            - /usr/local/lib/python3.8/dist-packages
             - /usr/local/bin
 
   unit_tests:
@@ -107,14 +100,13 @@ jobs:
       - run:
           name: run unit tests
           no_output_timeout: 20m
-          command: inv -e test --rerun-fails=2 --python-runtimes 3 --coverage --race --profile --cpus 8
-      # Codecov upload is failing in CircleCI with a "Please upload with the Codecov repository upload token to resolve issue" error.
-      # Public repositories don't need to use a token, it's a known issue often breaking Codecov, see  https://github.com/codecov/codecov-action/issues/837
-      # Adding a token would fix it but Datadog OAuth doesn't allow us to get a token, so we're disabling it for now.
-      # - run:
-      #     name: upload code coverage results
-      #     # Never fail on coverage upload
-      #     command: inv -e codecov || true
+          command: inv -e test --rerun-fails=2 --python-runtimes 3 --coverage --race --profile --cpus 8 --build-stdlib
+          environment:
+            GO_TEST_SKIP_FLAKE: "true"
+      - run:
+          name: upload code coverage results
+          # Never fail on coverage upload
+          command: inv -e codecov || true
 
   integration_tests:
     <<: *job_template
@@ -126,33 +118,6 @@ jobs:
       - run:
           name: run integration tests
           command: inv -e integration-tests --race --remote-docker
-
-  release_note:
-    <<: *job_template
-    steps:
-      - restore_cache: *restore_source
-      - restore_cache: *restore_deps
-      - run:
-          command: inv -e linter.releasenote
-          name: run PR check for release note
-
-  team_label:
-    <<: *job_template
-    steps:
-      - restore_cache: *restore_source
-      - restore_cache: *restore_deps
-      - run:
-          command: inv -e lint-teamassignment
-          name: run PR check for team assignment labels
-
-  milestone:
-    <<: *job_template
-    steps:
-      - restore_cache: *restore_source
-      - restore_cache: *restore_deps
-      - run:
-          command: inv -e lint-milestone
-          name: run PR check for milestone assignment
 
   go_linting:
     <<: *job_template
@@ -210,20 +175,6 @@ jobs:
           #SC2059: Don't use variables in the printf format string. Use printf "..%s.." "$foo".
           command: shellcheck --severity=info -e SC2059 -e SC2028 --shell=bash ./cmd/**/*.sh ./omnibus/package-scripts/*/*
 
-  python_linting:
-    <<: *job_template
-    steps:
-      - restore_cache: *restore_source
-      - restore_cache: *restore_deps
-      - run:
-          name: setting env vars for click
-          command: |
-              echo 'export LC_ALL="C.UTF-8"' >> $BASH_ENV
-              echo 'export LANG="C.UTF-8"' >> $BASH_ENV
-      - run:
-          name: lint python files
-          command: inv -e linter.python
-
   component_linting:
     <<: *job_template
     steps:
@@ -231,7 +182,7 @@ jobs:
       - restore_cache: *restore_deps
       - run:
           name: run component linting
-          command: inv -e lint-components
+          command: inv -e lint-components lint-fxutil-oneshot-test
 
   codeowner_linting:
     <<: *job_template
@@ -257,6 +208,7 @@ jobs:
 
   build_binaries:
     <<: *job_template
+    resource_class: large
     steps:
       - restore_cache: *restore_source
       - restore_cache: *restore_deps
@@ -302,27 +254,6 @@ workflows:
       - integration_tests:
           requires:
             - dependencies
-      - release_note:
-          filters:
-            branches:
-              ignore:
-                - main
-          requires:
-            - dependencies
-      - team_label:
-          filters:
-            branches:
-              ignore:
-                - main
-          requires:
-            - dependencies
-      - milestone:
-          filters:
-            branches:
-              ignore:
-                - main
-          requires:
-            - dependencies
       - go_linting:
           requires:
             - dependencies
@@ -336,9 +267,6 @@ workflows:
           requires:
             - dependencies
       - shell_linting:
-          requires:
-            - dependencies
-      - python_linting:
           requires:
             - dependencies
       - component_linting:
