refactor job to always run

diff --git a/.gitlab/do_not_merge.yml b/.gitlab/do_not_merge.yml
--- a/.gitlab/do_not_merge.yml
+++ b/.gitlab/do_not_merge.yml
@@ -1,4 +1,4 @@
-check-buildimages-suffix:
+do-not-merge:
   stage: .pre
   image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
   tags: ["arch:amd64"]
@@ -8,18 +8,19 @@ check-buildimages-suffix:
   - if: $CI_COMMIT_TAG
     when: never
   - !reference [.except_main_or_release_branch]
-  - if: |
-      $DATADOG_AGENT_BUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_WINBUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_ARMBUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_SYSPROBE_BUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_KERNEL_MATRIX_TESTING_BUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_NIKOS_BUILDIMAGES_SUFFIX != ""
-      || $DATADOG_AGENT_BTF_GEN_BUILDIMAGES_SUFFIX != ""
-      || $TEST_INFRA_DEFINITIONS_BUILDIMAGES_SUFFIX != ""
-    when: always
-  - when: never
+  - when: always
   script:
-    - echo "Pull request uses non-empty BUILDIMAGES_SUFFIX variable"
-    - echo "This workflow fails so that the pull request cannot be merged"
-    - exit 1
+      - |
+          if [ ! -z "$DATADOG_AGENT_BUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_WINBUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_ARMBUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_SYSPROBE_BUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_KERNEL_MATRIX_TESTING_BUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_NIKOS_BUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$DATADOG_AGENT_BTF_GEN_BUILDIMAGES_SUFFIX" ] ||
+             [ ! -z "$TEST_INFRA_DEFINITIONS_BUILDIMAGES_SUFFIX" ]; then
+            echo "Pull request uses non-empty BUILDIMAGES_SUFFIX variable"
+            echo "This workflow fails so that the pull request cannot be merged"
+            exit 1
+          fi
+      - exit 0
