Add package.compare-size invoke task

diff --git a/.gitlab/pkg_metrics.yml b/.gitlab/pkg_metrics.yml
--- a/.gitlab/pkg_metrics.yml
+++ b/.gitlab/pkg_metrics.yml
@@ -144,44 +144,29 @@ send_pkg_size-a7:
     - ls -l $OMNIBUS_PACKAGE_DIR
     - ls -l $OMNIBUS_PACKAGE_DIR_SUSE
     - source /root/.bashrc && conda activate ddpy3
-    - export failures=""
+    - export failures=0
     - export last_stable=$(inv release.get-release-json-value "last_stable::${MAJOR_VERSION}")
-    - |
-        compare_size() {
-            local package_type="${1}"
-            local max_diff="${2}"
-            local stable_package="${3}"
-            local new_package="${4}"
-
-            stable_size=$(stat --printf="%s" $stable_package)
-            new_size=$(stat --printf="%s" $new_package)
-            diff=$((new_size-stable_size))
-
-            if [ $diff -gt $max_diff ]; then
-                failures="${failures}${package_type} size increase is too large:\n"
-                failures="${failures}  New package size is ${new_size}B\n"
-                failures="${failures}  Stable package (${last_stable}) size is ${stable_size}B\n"
-                failures="${failures}  Diff is ${diff}B ${max_diff}B (max allowed diff)\n"
-            else
-              echo "${package_type} is OK"
-              echo "  New package size is ${new_size}B"
-              echo "  Stable package (${last_stable}) size is ${stable_size}B"
-              echo "  Diff is ${diff}B (max allowed diff is ${max_diff}B)"
-            fi
-        }
     # Get stable packages from S3 buckets & compare sizes
     # The loop assumes that all flavors start with "da", which is currently the case
+    # We want to run all package size comparisons before failing, so we set +e while doing the comparisons
+    # to get the error codes without exiting the shell.
     - |
         for flavor in ${FLAVORS}; do
             mkdir -p "/tmp/stable/${flavor}" "/tmp/stable/${flavor}/suse"
             curl -sSL "https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/${flavor}_${last_stable}-1_amd64.deb" -o "/tmp/stable/${flavor}/${flavor}_${last_stable}-1_amd64.deb"
             curl -sSL "https://s3.amazonaws.com/yum.datadoghq.com/stable/${MAJOR_VERSION}/x86_64/${flavor}-${last_stable}-1.x86_64.rpm" -o "/tmp/stable/${flavor}/${flavor}-${last_stable}-1.x86_64.rpm"
             curl -sSL "https://s3.amazonaws.com/yum.datadoghq.com/suse/stable/${MAJOR_VERSION}/x86_64/${flavor}-${last_stable}-1.x86_64.rpm" -o "/tmp/stable/${flavor}/suse/${flavor}-${last_stable}-1.x86_64.rpm"
-            compare_size "${flavor} deb" "${max_sizes[${flavor}]}" "/tmp/stable/${flavor}/${flavor}_${last_stable}-1_amd64.deb" "$OMNIBUS_PACKAGE_DIR/${flavor}_${MAJOR_VERSION}*_amd64.deb"
-            compare_size "${flavor} rpm" "${max_sizes[${flavor}]}" "/tmp/stable/${flavor}/${flavor}-${last_stable}-1.x86_64.rpm" "$OMNIBUS_PACKAGE_DIR/${flavor}-${MAJOR_VERSION}.*.x86_64.rpm"
-            compare_size "${flavor} suse rpm" "${max_sizes[${flavor}]}" "/tmp/stable/${flavor}/suse/${flavor}-${last_stable}-1.x86_64.rpm" "$OMNIBUS_PACKAGE_DIR_SUSE/${flavor}-${MAJOR_VERSION}.*.x86_64.rpm"
+            
+            set +e
+            inv package.compare-size --package-type "${flavor} deb" --last-stable "${last_stable}" --threshold "${max_sizes[${flavor}]}" --new-package "$OMNIBUS_PACKAGE_DIR/${flavor}_${MAJOR_VERSION}*_amd64.deb" --stable-package "/tmp/stable/${flavor}/${flavor}_${last_stable}-1_amd64.deb"
+            failures=$((${failures}+$?))
+            inv package.compare-size --package-type "${flavor} rpm" --last-stable "${last_stable}" --threshold "${max_sizes[${flavor}]}" --new-package "$OMNIBUS_PACKAGE_DIR/${flavor}-${MAJOR_VERSION}.*.x86_64.rpm" --stable-package "/tmp/stable/${flavor}/${flavor}-${last_stable}-1.x86_64.rpm"
+            failures=$((${failures}+$?))
+            inv package.compare-size --package-type "${flavor} suse rpm" --last-stable "${last_stable}" --threshold "${max_sizes[${flavor}]}" --new-package "$OMNIBUS_PACKAGE_DIR_SUSE/${flavor}-${MAJOR_VERSION}.*.x86_64.rpm" --stable-package "/tmp/stable/${flavor}/suse/${flavor}-${last_stable}-1.x86_64.rpm"
+            failures=$((${failures}+$?))
+            set -e
         done
-    - if [ "${failures}" != "" ]; then echo -e "${failures}" && false; fi
+    - if [ ! -z "${failures}" ]; then false; fi
 
 check_pkg_size-a6:
   extends: .check_pkg_size
