error handling of bootstrap

diff --git a/omnibus/package-scripts/installer-deb/postinst b/omnibus/package-scripts/installer-deb/postinst
--- a/omnibus/package-scripts/installer-deb/postinst
+++ b/omnibus/package-scripts/installer-deb/postinst
@@ -55,6 +55,9 @@ chown -R dd-installer:dd-installer ${INSTALL_DIR}
 chmod 777 ${PACKAGES_LOCK_DIR}
 
 # we currently allow failures to install the installer
-(bootstrap) || true
+exit_code=(bootstrap)
+if [ $exit_code -ne 0 ]; then
+    echo "Failed to bootstrap the installer: $exit_code" >&2
+fi
 
 exit 0
