Diagnose GitLab cache corruption on macOS

diff --git a/tools/bazel b/tools/bazel
--- a/tools/bazel
+++ b/tools/bazel
@@ -7,11 +7,35 @@ if [ -z "${BAZEL_REAL:-}" ] || [ "${BAZELISK_SKIP_WRAPPER:-}" != "true" ]; then
   exit 1
 fi
 
-# Restore `bazel`'s executable bit if it was not preserved (observed on macOS after zip extraction)
+# Try to understand why `bazel`'s executable bit is not preserved (observed on macOS after zip extraction)
 if [ ! -x "$BAZEL_REAL" ]; then
-  >&2 echo "🟡 Make bazel executable again"
-  >&2 ls -l "$BAZEL_REAL"
-  chmod +x "$BAZEL_REAL"
+  >&2 echo "🟡 Diagnostics for bazel corruption:"
+  cat /Users/ec2-user/.gitlab-runner/gitlab-runner.err.log \
+    | grep -Fv ddtool \
+    | grep -Fv github.com/DataDog/gitlab-runner-cirel/common \
+    | grep -Fv gitlab.com/gitlab-org/gitlab-runner/common \
+    | grep -Fv go/experiments \
+    | grep -Fv go/src/runtime/asm_amd64 \
+    | grep -Fv runtime.goexit \
+    | grep -Fv sent-log \
+    | grep -Fv watchExperiments \
+    | grep -Fv '409 Conflict' \
+    | grep -Fv 'Added job' \
+    | grep -Fv 'Checking for job' \
+    | grep -Fv 'Duration of' \
+    | grep -Fv 'Falling back to fetch strategy' \
+    | grep -Fv 'Job failed' \
+    | grep -Fv 'Job succeeded' \
+    | grep -Fv 'Removed job' \
+    | grep -Fv 'Submitting job' \
+    | grep -Fv 'Updating job' \
+    | grep -v '^"$' >&2 || true
+
+  rm -rfv /Users/ec2-user/cache/DataDog/datadog-agent/bazel-gitlab-runner-macos-datadog-agent-ventura-a* || true
+  log show --predicate 'eventMessage contains "hardware" OR eventMessage contains "ECC" OR eventMessage contains "memory error"' --last 7d >"$XDG_CACHE_HOME/diag-ev.log" || true
+  log show --predicate 'messageType == error' --info --debug --last boot >"$XDG_CACHE_HOME/diag-mt.log" || true
+  log show --predicate 'processImagePath contains "kernel"' --style syslog --last 1d | grep -i "error\|panic\|ecc" >"$XDG_CACHE_HOME/diag-pip.log" || true
+  system_profiler SPHardwareDataType SPMemoryDataType >"$XDG_CACHE_HOME/diag-sp.log" || true
 fi
 
 # Not in CI: simply execute `bazel` - done
