attempt to fix golang_deps_diff

diff --git a/.gitlab/source_test/golang_deps_diff.yml b/.gitlab/source_test/golang_deps_diff.yml
--- a/.gitlab/source_test/golang_deps_diff.yml
+++ b/.gitlab/source_test/golang_deps_diff.yml
@@ -25,7 +25,9 @@ golang_deps_diff:
 
 golang_deps_commenter:
   stage: source_test
-  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/pr-commenter:2
+  image:
+    name: "486234852809.dkr.ecr.us-east-1.amazonaws.com/pr-commenter:3"
+    entrypoint: [""] # disable entrypoint script for the pr-commenter image
   tags: ["arch:amd64", "specific:true"]
   rules:
     - !reference [.on_dev_branches]
@@ -36,9 +38,26 @@ golang_deps_commenter:
     FF_KUBERNETES_HONOR_ENTRYPOINT: false
   script: # ignore error message about no PR, because it happens for dev branches without PRs
     - echo "${CI_COMMIT_REF_NAME}"
+    # Check if the report file exists and has content
+    - |
+      if [[ ! -s "deps-report.md" ]]
+      then
+          echo "ERROR: Go deps report not found -- no PR comment posted"
+          exit 1
+      fi
+    # Transform the Markdown report into a valid JSON string
+    - cat deps-report.md | sed -z 's/\n/\\n/g' | sed -z 's/"/\\"/g' > deps-report-json-string.txt
+    # Create JSON payload for the pr-commenter service
+    - PR_COMMENT_JSON_PAYLOAD='{"org":"DataDog", "repo":"datadog-agent", "commit":"'"${CI_COMMIT_SHA}"'", "header":"Go Package Import Differences", "message":"'"$(cat deps-report-json-string.txt)"'"}'
+    - printf "%s\n" "PR comment JSON payload: ${PR_COMMENT_JSON_PAYLOAD}"
+    # Send HTTP request to pr-commenter service
     - |
       set +e
-      out=$(pr-commenter --for-pr="${CI_COMMIT_REF_NAME}" --header="Go Package Import Differences" --infile deps-report.md 2>&1)
+      out=$(curl https://pr-commenter.us1.ddbuild.io/internal/cit/pr-comment \
+          -H "$(authanywhere)" \
+          -H "X-DdOrigin: curl" \
+          -X PATCH \
+          -d "${PR_COMMENT_JSON_PAYLOAD}")
       exitcode=$?
       set -e
       if [ -n "${out}" ]; then
