[packaging][rhel] Restart only once at the very end of the install
i.e. in the posttrans script. Without this change the agent would
always be restarted twice during an install.

diff --git a/omnibus/package-scripts/datadog-agent6/postinst b/omnibus/package-scripts/datadog-agent6/postinst
--- a/omnibus/package-scripts/datadog-agent6/postinst
+++ b/omnibus/package-scripts/datadog-agent6/postinst
@@ -21,9 +21,13 @@ fi
 
 # Linux installation
 if [ "$DISTRIBUTION" != "Darwin" ]; then
+    if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
+        DISTRIBUTION_FAMILY="Debian"
+    fi
+
     CONFIG_DIR=/etc/dd-agent
 
-    if [ -f "/etc/debian_version" ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
+    if [ "$DISTRIBUTION_FAMILY" == "Debian" ]; then
         set -e
         case "$1" in
             configure)
@@ -69,22 +73,26 @@ if [ "$DISTRIBUTION" != "Darwin" ]; then
         exit 1
     fi
 
-    # TODO: Use a configcheck command on the agent to determine if it's safe to restart,
-    # and avoid restarting when a check conf is invalid
-    if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
-        echo "(Re)starting $SERVICE_NAME now..."
-        if command -v systemctl >/dev/null 2>&1; then
-            systemctl restart $SERVICE_NAME || true
-        elif command -v initctl >/dev/null 2>&1; then
-            initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
+    # Restart the agent here on Debian platforms
+    # On RHEL, the restart is done in the posttrans script
+    if [ "$DISTRIBUTION_FAMILY" == "Debian" ]; then
+        # TODO: Use a configcheck command on the agent to determine if it's safe to restart,
+        # and avoid restarting when a check conf is invalid
+        if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
+            echo "(Re)starting $SERVICE_NAME now..."
+            if command -v systemctl >/dev/null 2>&1; then
+                systemctl restart $SERVICE_NAME || true
+            elif command -v initctl >/dev/null 2>&1; then
+                initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
+            else
+                echo "[ ${Red}FAILED ${RCol}]\tUnsupported init system."
+                exit 1
+            fi
         else
-            echo "[ ${Red}FAILED ${RCol}]\tUnsupported init system."
-            exit 1
+            # No datadog.yaml file is present. This is probably a clean install made with the
+            # step-by-step instructions/an automation tool, and the config file will be added next.
+            echo "No datadog.yaml file detected, not starting the agent"
         fi
-    else
-        # No datadog.yaml file is present. This is probably a clean install made with the
-        # step-by-step instructions/an automation tool, and the config file will be added next.
-        echo "No datadog.yaml file detected, not starting the agent"
     fi
 else
     echo "macOS: Not implemented yet"
