Better error catching

diff --git a/.github/workflows/add_milestone.yml b/.github/workflows/add_milestone.yml
--- a/.github/workflows/add_milestone.yml
+++ b/.github/workflows/add_milestone.yml
@@ -13,35 +13,42 @@ jobs:
     steps:
       - name: Get PR from which the commit is from
         id: source-pr
-        run: echo "NUMBER=$(gh pr list --search "$GITHUB_SHA" --state merged --json url --jq '.[0].url' | sed 's|.*pull/\(.*\)|\1|g')" >> "$GITHUB_OUTPUT"
+        run: |
+          NUMBER=$(gh pr list --search "$GITHUB_SHA" --state merged --json url --jq '.[0].url' | sed 's|.*pull/\(.*\)|\1|g')
+          if [ -z "$NUMBER" ]; then
+            echo "Error: Couldn't find the PR commit $GITHUB_SHA originating from, milestone not assigned."
+            exit 1
+          fi
+          echo "NUMBER=$NUMBER" >> "$GITHUB_OUTPUT"
       - name: Get repo current milestone
         id: current-milestone
         run: |
           if [[ ${GITHUB_REF##*/} =~ ^7\.[0-9]+\.[0-9]+$ ]]; then
             # If we're on a release branch, set the milestone to the latest release milestone found.
             MILESTONE=$(gh release list | grep -o $(echo ${GITHUB_REF##*/} | sed 's/x/[0-9]*/g') | sort -uV | tail -1)
+            if [ -z "$MILESTONE" ]; then
+              echo "Error: Couldn't get the latest release milestone from Github."
+              exit 1
+            fi
           else
             # Else use the current_milestone field in the release.json file.
             MILESTONE=$(cat release.json | jq -r .current_milestone)" >> "$GITHUB_OUTPUT"
+            if [ -z "$MILESTONE" ]; then
+              echo "Error: Couldn't find the current_milestone field in the release.json file."
+              exit 1
+            fi
+          fi
+          if [[ $MILESTONE !~ ^7\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Malformed milestone $MILESTONE. It should be of the form '7.x.y'."
+            exit 1
           fi
           echo "MILESTONE=$MILESTONE" >> "$GITHUB_OUTPUT"
 
       - name: Set the merged PR milestone to current_milestone from release.json
         run: |
-          if [ -z "$NUMBER" ]; then
-            echo "Error: Couldn't find the PR commit $GITHUB_SHA originating from, milestone not assigned."
-            exit 1
-          elif [ -z "$MILESTONE" ]; then
-            echo "Error: Couldn't find the current_milestone field in the release.json file."
-            exit 1
-          elif [[ $MILESTONE !~ ^7\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Malformed milestone $MILESTONE. It should be of the form '7.x.y'."
-            exit 1
-          else
-            echo "Setting milestone $MILESTONE to PR #$NUMBER."
-            gh issue edit "$NUMBER" --milestone "$MILESTONE"
-            exit 0
-          fi
+          echo "Setting milestone $MILESTONE to PR #$NUMBER."
+          gh issue edit "$NUMBER" --milestone "$MILESTONE"
+          exit 0
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
