[auto-team-labels] Set up auto team label assignation as github workflow

diff --git a/.github/workflows/label-analysis.yml b/.github/workflows/label-analysis.yml
--- a/.github/workflows/label-analysis.yml
+++ b/.github/workflows/label-analysis.yml
@@ -25,6 +25,42 @@ jobs:
           labels="${{join(github.event.pull_request.labels.*.name, ' ')}}"
           echo "Fetched labels for PR ${{github.event.number}}: $labels"
           echo "LABELS=$labels" >> "$GITHUB_OUTPUT"
+  assign-team-label:
+    if: github.triggering_actor != 'dd-devflow[bot]'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r tasks/requirements.txt
+      - name: Add get-changed-files dependency
+        id: files
+        uses: jitterbit/get-changed-files@v1
+        with:
+          format: 'csv'
+      - name: Auto assign team label
+        run: |
+          command=( inv -e github.deduce-team-label )
+          mapfile -d ',' -t files < <(printf '%s,' '${{ steps.files.outputs.all }}')
+          for file in "${files[@]}"; do
+            command+=( --changed-files="$file" )
+          done
+          echo "COMMAND: ${command[@]}"
+          labelname="$("${command[@]}")"
+          exitcode="$?"
+          if [ "$exitcode" != 0 ]; then
+            echo "Cannot deduce team (got exit code $exitcode)"
+            exit
+          fi
+          gh pr edit '${{ github.event.number }}' --add-label "$labelname"
   team-label:
     needs: fetch-labels
     if: github.triggering_actor != 'dd-devflow[bot]'
